'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
/* eslint-disable quote-props */

exports.default = {
  'Thread': '01',
  'Stick': '02',
  'Pelt': '03',
  'Bone': '04',
  'Coal': '05',
  'Charcoal': '06',
  'Powder': '07',
  'Iron ore': '08',
  'Cloth': '09',
  'Silver ore': '10',
  'Bauxite': '11',
  'Magic stone': '13',
  'Sapphire': '15',
  'Solvent': '16',
  'Ruby': '17',
  'Hardener': '18',
  'Steel': '19',
  'Leather': '20',
  'Bone powder': '21',
  'String': '22',
  'Coke': '23',
  'Purified powder': '24',
  'Silver alloy': '25',
  'Steel mold': '27',
  'Silver mold': '28',
  'Blacksmith frame': '29',
  'Artisan frame': '30',
  'Rope': '31',
  'Silver frame': '32',
  'Metal plate': '33',
  'Metallic fiber': '34',
  'Crafted leather': '35',
  'Stinky Sumac': '39',
  'Mercy Sassafras': '40',
  'Cliff Rue': '41',
  'Love Creeper': '42',
  'Wolf Root': '43',
  'Swamp Lavender': '44',
  'White Blossom': '45',
  'Ilaves': '46',
  'Ephijora': '47',
  'Storm Hyssop': '48',
  'Cave Garlic': '49',
  'Yellow Seed': '50',
  'Tecceagrass': '51',
  'Spring Bay Leaf': '52',
  'Ash Rosemary': '53',
  'Sanguine Parsley': '54',
  'Sun Tarragon': '55',
  'Maccunut': '56',
  'Dragon Seed': '57',
  'Queen\'s Pepper': '58',
  'Plasma of abyss': '59',
  'Ultramarine dust': '60',
  'Ethereal bone': '61',
  'Itacory': '62',
  'Assassin Vine': '63',
  'Kloliarway': '64',
  'Astrulic': '65',
  'Flammia Nut': '66',
  'Plexisop': '67',
  'Mammoth Dill': '68',
  'Silver dust': '69',
  'Hay': '518',
  'Corn': '519',
  'Hamsters': '520',
  'Cheese': '521',
  'Zombie Chest': 'ch1',
  'Ancient Chest': 'ch2',
  'Vial of Rage': 'p01',
  'Potion of Rage': 'p02',
  'Bottle of Rage': 'p03',
  'Vial of Peace': 'p04',
  'Potion of Peace': 'p05',
  'Bottle of Peace': 'p06',
  'Vial of Greed': 'p07',
  'Potion of Greed': 'p08',
  'Bottle of Greed': 'p09',
  'Vial of Nature': 'p10',
  'Potion of Nature': 'p11',
  'Bottle of Nature': 'p12',
  'Vial of Mana': 'p13',
  'Potion of Mana': 'p14',
  'Bottle of Mana': 'p15',
  'Vial of Twilight': 'p16',
  'Potion of Twilight': 'p17',
  'Bottle of Twilight': 'p18',
  'Vial of Morph': 'p19',
  'Potion of Morph': 'p20',
  'Bottle of Morph': 'p21',
  'Pouch of gold': '100',
  'Wrapping': '501',
  'Wooden arrows': '504',
  'Wooden arrows pack': '505',
  'Bottle of Remedy': '506',
  'Remedy pack': '507',
  'Bottle of Poison': '508',
  'Poison pack': '509',
  'Steel arrows': '510',
  'Steel arrows pack': '511',
  'Silver arrows': '512',
  'Silver arrows pack': '513',
  '🎟Gift Coupon \'Pig\'': '514',
  '🎟Gift Coupon \'Horse\'': '515',
  '🎟Gift Coupon \'Owl\'': '516',
  '🎟Gift Coupon \'Mouse\'': '517',
  '🎟Gift Coupon \'Gopher\'': '522',
  '🎟Gift Coupon \'Ants\'': '523',
  '🎟Gift Coupon \'Spider\'': '524',
  '🎟Gift Coupon \'Haunted\'': '525',
  '🎟Gift Coupon \'Camel\'': '526',
  'Cloth jacket': 'a01',
  'Leather shirt': 'a02',
  'Chain mail': 'a03',
  'Silver cuirass': 'a04',
  'Mithril armor': 'a05',
  'Hat': 'a06',
  'Leather hood': 'a07',
  'Steel helmet': 'a08',
  'Silver helmet': 'a09',
  'Mithril helmet': 'a10',
  'Sandals': 'a11',
  'Leather shoes': 'a12',
  'Steel boots': 'a13',
  'Silver boots': 'a14',
  'Mithril boots': 'a15',
  'Gloves': 'a16',
  'Leather gloves': 'a17',
  'Steel gauntlets': 'a18',
  'Silver gauntlets': 'a19',
  'Mithril gauntlets': 'a20',
  'Wooden shield': 'a21',
  'Skeleton Buckler': 'a22',
  'Bronze shield': 'a23',
  'Silver shield': 'a24',
  'Mithril shield': 'a25',
  'Royal Guard Cape': 'a26',
  'Order Armor': 'a27',
  'Order Helmet': 'a28',
  'Order Boots': 'a29',
  'Order Gauntlets': 'a30',
  'Order Shield': 'a31',
  'Hunter Armor': 'a32',
  'Hunter Helmet': 'a33',
  'Hunter Boots': 'a34',
  'Hunter Gloves': 'a35',
  'Clarity Robe': 'a36',
  'Clarity Circlet': 'a37',
  'Clarity Shoes': 'a38',
  'Clarity Bracers': 'a39',
  '✏️Pencil of Truth': 'a40',
  'Crusader Armor': 'a45',
  'Crusader Helmet': 'a46',
  'Crusader Boots': 'a47',
  'Crusader Gauntlets': 'a48',
  'Crusader Shield': 'a49',
  'Royal Armor': 'a50',
  'Royal Helmet': 'a51',
  'Royal Boots': 'a52',
  'Royal Gauntlets': 'a53',
  'Royal Shield': 'a54',
  'Ghost Armor': 'a55',
  'Ghost Helmet': 'a56',
  'Ghost Boots': 'a57',
  'Ghost Gloves': 'a58',
  'Lion Armor': 'a59',
  'Lion Helmet': 'a60',
  'Lion Boots': 'a61',
  'Lion Gloves': 'a62',
  'Demon Robe': 'a63',
  'Demon Circlet': 'a64',
  'Demon Shoes': 'a65',
  'Demon Bracers': 'a66',
  'Divine Robe': 'a67',
  'Divine Circlet': 'a68',
  'Divine Shoes': 'a69',
  'Divine Bracers': 'a70',
  'Storm Cloak': 'a71',
  'Durable Cloak': 'a72',
  'Blessed Cloak': 'a73',
  'Hiking Jar': 'a74',
  'Hiking Bag': 'a75',
  'Zombie Box': 'bx3',
  'Hunter Kit': 'hk',
  'Champion blade': 'k01',
  'Trident blade': 'k02',
  'Hunter shaft': 'k03',
  'War hammer head': 'k04',
  'Hunter blade': 'k05',
  'Order Armor piece': 'k06',
  'Order Helmet fragment': 'k07',
  'Order Boots part': 'k08',
  'Order Gauntlets part': 'k09',
  'Order shield part': 'k10',
  'Hunter Armor part': 'k11',
  'Hunter Helmet fragment': 'k12',
  'Hunter Boots part': 'k13',
  'Hunter Gloves part': 'k14',
  'Clarity Robe piece': 'k15',
  'Clarity Circlet fragment': 'k16',
  'Clarity Shoes part': 'k17',
  'Clarity Bracers part': 'k18',
  'Thundersoul blade': 'k19',
  'Doomblade blade': 'k20',
  'Eclipse blade': 'k21',
  'Guard\'s blade': 'k22',
  'Composite Bow shaft': 'k25',
  'Lightning Bow shaft': 'k26',
  'Hailstorm Bow shaft': 'k27',
  'Imperial Axe head': 'k28',
  'Skull Crusher head': 'k29',
  'Dragon Mace head': 'k30',
  'Ghost blade': 'k31',
  'Lion blade': 'k32',
  'Crusader Armor piece': 'k33',
  'Crusader Helmet fragment': 'k34',
  'Crusader Boots part': 'k35',
  'Crusader Gauntlets part': 'k36',
  'Crusader shield part': 'k37',
  'Royal Armor piece': 'k38',
  'Royal Helmet fragment': 'k39',
  'Royal Boots part': 'k40',
  'Royal Gauntlets part': 'k41',
  'Royal shield part': 'k42',
  'Ghost Armor part': 'k43',
  'Ghost Helmet fragment': 'k44',
  'Ghost Boots part': 'k45',
  'Ghost Gloves part': 'k46',
  'Lion Armor part': 'k47',
  'Lion Helmet fragment': 'k48',
  'Lion Boots part': 'k49',
  'Lion Gloves part': 'k50',
  'Demon Robe piece': 'k51',
  'Demon Circlet fragment': 'k52',
  'Demon Shoes part': 'k53',
  'Demon Bracers part': 'k54',
  'Divine Robe piece': 'k55',
  'Divine Circlet fragment': 'k56',
  'Divine Shoes part': 'k57',
  'Divine Bracers part': 'k58',
  'Storm Cloak part': 'k59',
  'Durable Cloak part': 'k60',
  'Blessed Cloak part': 'k61',

  'Vial of Oblivion': 'pl1',
  'Bottle of Oblivion': 'pl3',
  'Accuracy Pill': 'pap',
  'Garlic Stew': 'pgs',
  'Holy Water': 'phw',
  'Monster Pheromones': 'pmp',
  'Silver Blood': 'psb',
  'Vial of Defiance': 'pvd',
  'Champion Sword recipe': 'r01',
  'Trident recipe': 'r02',
  'Hunter Bow recipe': 'r03',
  'War hammer recipe': 'r04',
  'Hunter Dagger recipe': 'r05',
  'Order Armor recipe': 'r06',
  'Order Helmet recipe': 'r07',
  'Order Boots recipe': 'r08',
  'Order Gauntlets recipe': 'r09',
  'Order shield recipe': 'r10',
  'Hunter Armor recipe': 'r11',
  'Hunter Helmet recipe': 'r12',
  'Hunter Boots recipe': 'r13',
  'Hunter Gloves recipe': 'r14',
  'Clarity Robe recipe': 'r15',
  'Clarity Circlet recipe': 'r16',
  'Clarity Shoes recipe': 'r17',
  'Clarity Bracers recipe': 'r18',
  'Thundersoul Sword recipe': 'r19',
  'Doomblade Sword recipe': 'r20',
  'Eclipse recipe': 'r21',
  'Guard\'s Spear recipe': 'r22',
  'King\'s Defender recipe': 'r23',
  'Raging Lance recipe': 'r24',
  'Composite Bow recipe': 'r25',
  'Lightning Bow recipe': 'r26',
  'Hailstorm Bow recipe': 'r27',
  'Imperial Axe recipe': 'r28',
  'Skull Crusher recipe': 'r29',
  'Dragon Mace recipe': 'r30',
  'Ghost Dagger recipe': 'r31',
  'Lion Knife recipe': 'r32',
  'Crusader Armor recipe': 'r33',
  'Crusader Helmet recipe': 'r34',
  'Crusader Boots recipe': 'r35',
  'Crusader Gauntlets recipe': 'r36',
  'Crusader shield recipe': 'r37',
  'Royal Armor recipe': 'r38',
  'Royal Helmet recipe': 'r39',
  'Royal Boots recipe': 'r40',
  'Royal Gauntlets recipe': 'r41',
  'Royal shield recipe': 'r42',
  'Ghost Armor recipe': 'r43',
  'Ghost Helmet recipe': 'r44',
  'Ghost Boots recipe': 'r45',
  'Ghost Gloves recipe': 'r46',
  'Lion Armor recipe': 'r47',
  'Lion Helmet recipe': 'r48',
  'Lion Boots recipe': 'r49',
  'Lion Gloves recipe': 'r50',
  'Demon Robe recipe': 'r51',
  'Demon Circlet recipe': 'r52',
  'Demon Shoes recipe': 'r53',
  'Demon Bracers recipe': 'r54',
  'Divine Robe recipe': 'r55',
  'Divine Circlet recipe': 'r56',
  'Divine Shoes recipe': 'r57',
  'Divine Bracers recipe': 'r58',
  'Storm Cloak recipe': 'r59',
  'Durable Cloak recipe': 'r60',
  'Blessed Cloak recipe': 'r61',
  '📕Scroll of Rage': 's01',
  '📕Scroll of Peace': 's02',
  '📗Scroll of Rage': 's03',
  '📗Scroll of Peace': 's04',
  '📘Scroll of Rage': 's05',
  '📘Scroll of Peace': 's06',
  '📙Scroll of Rage': 's07',
  '📙Scroll of Peace': 's08',
  '📕Rare Scroll of Rage': 's11',
  '📕Rare Scroll of Peace': 's12',
  '📗Rare Scroll of Rage': 's13',
  '📗Rare Scroll of Peace': 's14',
  '📘Rare Scroll of Rage': 's15',
  '📘Rare Scroll of Peace': 's16',
  '📙Rare Scroll of Rage': 's17',
  '📙Rare Scroll of Peace': 's18',
  'Elder\'s recommendation': 'er',
  'Proof of Loyalty': 'pol',
  'Torch': 'tch',
  'Loyalty Trophy': 'tlt',
  'Wooden sword': 'w01',
  'Short sword': 'w02',
  'Long sword': 'w03',
  'Widow sword': 'w04',
  'Knight\'s sword': 'w05',
  'Elven sword': 'w06',
  'Rapier': 'w07',
  'Short spear': 'w08',
  'Long spear': 'w09',
  'Lance': 'w10',
  'Elven spear': 'w11',
  'Halberd': 'w12',
  'Kitchen knife': 'w13',
  'Battle knife': 'w14',
  'Steel dagger': 'w15',
  'Silver dagger': 'w16',
  'Mithril dagger': 'w17',
  'Short Bow': 'w18',
  'Wooden Bow': 'w19',
  'Long Bow': 'w20',
  'Elven Bow': 'w21',
  'Forest Bow': 'w22',
  'Club': 'w23',
  'Bone club': 'w24',
  'Heavy club': 'w25',
  'Steel axe': 'w26',
  'Mithril axe': 'w27',
  'Champion Sword': 'w28',
  'Trident': 'w29',
  'Hunter Bow': 'w30',
  'War hammer': 'w31',
  'Hunter dagger': 'w32',
  'Thundersoul Sword': 'w33',
  'Doomblade Sword': 'w34',
  'Guard\'s Spear': 'w36',
  'King\'s Defender': 'w37',
  'Composite Bow': 'w39',
  'Lightning Bow': 'w40',
  'Hailstorm Bow': 'w41',
  'Imperial Axe': 'w42',
  'Skull Crusher': 'w43',
  'Dragon Mace': 'w44',
  'Ghost dagger': 'w45',
  'Lion knife': 'w46'
};