/* eslint-disable quote-props */

export default {
  'Thread': '01',
  'Stick': '02',
  'Pelt': '03',
  'Bone': '04',
  'Coal': '05',
  'Charcoal': '06',
  'Powder': '07',
  'Iron ore': '08',
  'Cloth': '09',
  'Silver ore': '10',
  'Bauxite': '11',
  'Magic stone': '13',
  'Wooden shaft': '14',
  'Sapphire': '15',
  'Solvent': '16',
  'Ruby': '17',
  'Hardener': '18',
  'Steel': '19',
  'Leather': '20',
  'Bone powder': '21',
  'String': '22',
  'Coke': '23',
  'Purified powder': '24',
  'Silver alloy': '25',
  'Steel mold': '27',
  'Silver mold': '28',
  'Blacksmith frame': '29',
  'Artisan frame': '30',
  'Rope': '31',
  'Silver frame': '32',
  'Metal plate': '33',
  'Metallic fiber': '34',
  'Crafted leather': '35',
  'Quality Cloth': '36',
  'Blacksmith mold': '37',
  'Artisan mold': '38',
  'Stinky Sumac': '39',
  'Mercy Sassafras': '40',
  'Cliff Rue': '41',
  'Love Creeper': '42',
  'Wolf Root': '43',
  'Swamp Lavender': '44',
  'White Blossom': '45',
  'Ilaves': '46',
  'Ephijora': '47',
  'Storm Hyssop': '48',
  'Cave Garlic': '49',
  'Yellow Seed': '50',
  'Tecceagrass': '51',
  'Spring Bay Leaf': '52',
  'Ash Rosemary': '53',
  'Sanguine Parsley': '54',
  'Sun Tarragon': '55',
  'Maccunut': '56',
  'Dragon Seed': '57',
  'Queen\'s Pepper': '58',
  'Plasma of abyss': '59',
  'Ultramarine dust': '60',
  'Ethereal bone': '61',
  'Itacory': '62',
  'Assassin Vine': '63',
  'Kloliarway': '64',
  'Astrulic': '65',
  'Flammia Nut': '66',
  'Plexisop': '67',
  'Mammoth Dill': '68',
  'Silver dust': '69',
  'Hay': '618',
  'Corn': '619',
  'Hamsters': '620',
  'Cheese': '621',
  'Zombie Chest': 'ch1',
  'Ancient Chest': 'ch2',
  'Vial of Rage': 'p01',
  'Potion of Rage': 'p02',
  'Bottle of Rage': 'p03',
  'Vial of Peace': 'p04',
  'Potion of Peace': 'p05',
  'Bottle of Peace': 'p06',
  'Vial of Greed': 'p07',
  'Potion of Greed': 'p08',
  'Bottle of Greed': 'p09',
  'Vial of Nature': 'p10',
  'Potion of Nature': 'p11',
  'Bottle of Nature': 'p12',
  'Vial of Mana': 'p13',
  'Potion of Mana': 'p14',
  'Bottle of Mana': 'p15',
  'Vial of Twilight': 'p16',
  'Potion of Twilight': 'p17',
  'Bottle of Twilight': 'p18',
  'Vial of Morph': 'p19',
  'Potion of Morph': 'p20',
  'Bottle of Morph': 'p21',
  'Pouch of gold': '100',
  'Wrapping': '501',
  'Wooden arrows': '504',
  'Wooden arrows pack': '505',
  'Bottle of Remedy': '506',
  'Remedy pack': '507',
  'Bottle of Poison': '508',
  'Poison pack': '509',
  'Steel arrows': '510',
  'Steel arrows pack': '511',
  'Silver arrows': '512',
  'Silver arrows pack': '513',
  'Broad arrow': '514',
  'Broad arrows pack': '515',
  'Heavy arrow': '516',
  'Heavy arrows pack': '517',
  'Compound arrow': '518',
  'Compound arrows pack': '519',
  'Cloth jacket': 'a01',
  'Leather shirt': 'a02',
  'Hat': 'a06',
  'Leather hood': 'a07',
  'Sandals': 'a11',
  'Leather shoes': 'a12',
  'Steel boots': 'a13',
  'Gloves': 'a16',
  'Leather gloves': 'a17',
  'Steel gauntlets': 'a18',
  'Wooden shield': 'a21',
  'Skeleton Buckler': 'a22',
  'Hiking Jar': 'a74',
  'Hiking Bag': 'a75',
  'Zombie Box': 'bx3',
  'Hunter Kit': 'hk',

  'Vial of Oblivion': 'pl1',
  'Bottle of Oblivion': 'pl3',
  'Accuracy Pill': 'pap',
  'Garlic Stew': 'pgs',
  'Holy Water': 'phw',
  'Monster Pheromones': 'pmp',
  'Silver Blood': 'psb',
  'Vial of Defiance': 'pvd',
  'Elder\'s recommendation': 'er',
  'Proof of Loyalty': 'pol',
  'Torch': 'tch',
  'Loyalty Trophy': 'tlt',
  'Wooden sword': 'w01',
  'Short spear': 'w08',
  'Kitchen knife': 'w13',
  'Battle knife': 'w14',
  'Short Bow': 'w18',
  'Club': 'w23',
  'Champion Sword recipe': 'r01',
  'Trident recipe': 'r02',
  'Hunter Bow recipe': 'r03',
  'War hammer recipe': 'r04',
  'Hunter Dagger recipe': 'r05',
  'Order Armor recipe': 'r06',
  'Order Helmet recipe': 'r07',
  'Order Boots recipe': 'r08',
  'Order Gauntlets recipe': 'r09',
  'Order shield recipe': 'r10',
  'Hunter Armor recipe': 'r11',
  'Hunter Helmet recipe': 'r12',
  'Hunter Boots recipe': 'r13',
  'Hunter Gloves recipe': 'r14',
  'Clarity Robe recipe': 'r15',
  'Clarity Circlet recipe': 'r16',
  'Clarity Shoes recipe': 'r17',
  'Clarity Bracers recipe': 'r18',
  'Thundersoul Sword recipe': 'r19',
  'Doomblade Sword recipe': 'r20',
  'Eclipse recipe': 'r21',
  'Guard\'s Spear recipe': 'r22',
  'King\'s Defender recipe': 'r23',
  'Raging Lance recipe': 'r24',
  'Composite Bow recipe': 'r25',
  'Lightning Bow recipe': 'r26',
  'Hailstorm Bow recipe': 'r27',
  'Imperial Axe recipe': 'r28',
  'Skull Crusher recipe': 'r29',
  'Dragon Mace recipe': 'r30',
  'Ghost dagger recipe': 'r31',
  'Lion Knife recipe': 'r32',
  'Crusader Armor recipe': 'r33',
  'Crusader Helmet recipe': 'r34',
  'Crusader Boots recipe': 'r35',
  'Crusader Gauntlets recipe': 'r36',
  'Crusader shield recipe': 'r37',
  'Royal Armor recipe': 'r38',
  'Royal Helmet recipe': 'r39',
  'Royal Boots recipe': 'r40',
  'Royal Gauntlets recipe': 'r41',
  'Royal shield recipe': 'r42',
  'Ghost Armor recipe': 'r43',
  'Ghost Helmet recipe': 'r44',
  'Ghost Boots recipe': 'r45',
  'Ghost Gloves recipe': 'r46',
  'Lion Armor recipe': 'r47',
  'Lion Helmet recipe': 'r48',
  'Lion Boots recipe': 'r49',
  'Lion Gloves recipe': 'r50',
  'Demon Robe recipe': 'r51',
  'Demon Circlet recipe': 'r52',
  'Demon Shoes recipe': 'r53',
  'Demon Bracers recipe': 'r54',
  'Divine Robe recipe': 'r55',
  'Divine Circlet recipe': 'r56',
  'Divine Shoes recipe': 'r57',
  'Divine Bracers recipe': 'r58',
  'Storm Cloak recipe': 'r59',
  'Durable Cloak recipe': 'r60',
  'Blessed Cloak recipe': 'r61',
  'Council Armor recipe': 'r78',
  'Council Helmet recipe': 'r79',
  'Council Boots recipe': 'r80',
  'Council Gauntlets recipe': 'r81',
  'Council Shield recipe': 'r82',
  'Griffin Armor recipe': 'r83',
  'Griffin Helmet recipe': 'r84',
  'Griffin Boots recipe': 'r85',
  'Griffin Gloves recipe': 'r86',
  'Celestial Armor recipe': 'r87',
  'Celestial Helmet recipe': 'r88',
  'Celestial Boots recipe': 'r89',
  'Celestial Bracers recipe': 'r90',
  'Griffin Knife recipe': 'r91',
  'Minotaur Sword recipe': 'r92',
  'Phoenix Sword recipe': 'r93',
  'Heavy Fauchard recipe': 'r94',
  'Guisarme recipe': 'r95',
  'Meteor Bow recipe': 'r96',
  'Nightfall Bow recipe': 'r97',
  'Black Morningstar recipe': 'r98',
  'Maiming Bulawa recipe': 'r99',
  'Assault Cape recipe': 'r100',
  'Craftsman Apron recipe': 'r101',
  'Stoneskin Cloak recipe': 'r102',
  'Poniard recipe': 'r103',
  'Lightbane Katana recipe': 'r104',
  'Doom Warglaive recipe': 'r105',
  'Decimation Harpoon recipe': 'r106',
  'Sinister Ranseur recipe': 'r107',
  'Heartstriker Bow recipe': 'r108',
  'Windstalker Bow recipe': 'r109',
  'Malificent Maul recipe': 'r110',
  'Brutalizer Flail recipe': 'r111',
  'Manticore Armor recipe': 'r112',
  'Manticore Helmet recipe': 'r113',
  'Manticore Boots recipe': 'r114',
  'Manticore Gloves recipe': 'r115',
  'Overseer Armor recipe': 'r116',
  'Overseer Helmet recipe': 'r117',
  'Overseer Boots recipe': 'r118',
  'Overseer Gauntlets recipe': 'r119',
  'Overseer Shield recipe': 'r120',
  'Discarnate Robe recipe': 'r121',
  'Discarnate Circlet recipe': 'r122',
  'Discarnate Shoes recipe': 'r123',
  'Discarnate Bracers recipe': 'r124',

  'Champion blade': 'k01',
  'Trident blade': 'k02',
  'Hunter shaft': 'k03',
  'War hammer head': 'k04',
  'Hunter blade': 'k05',
  'Order Armor piece': 'k06',
  'Order Helmet fragment': 'k07',
  'Order Boots part': 'k08',
  'Order Gauntlets part': 'k09',
  'Order shield part': 'k10',
  'Hunter Armor part': 'k11',
  'Hunter Helmet fragment': 'k12',
  'Hunter Boots part': 'k13',
  'Hunter Gloves part': 'k14',
  'Clarity Robe piece': 'k15',
  'Clarity Circlet fragment': 'k16',
  'Clarity Shoes part': 'k17',
  'Clarity Bracers part': 'k18',
  'Thundersoul blade': 'k19',
  'Doomblade blade': 'k20',
  'Eclipse blade': 'k21',
  'Guard\'s blade': 'k22',
  'King\'s Defender blade': 'k23',
  'Raging Lance blade': 'k24',
  'Composite Bow shaft': 'k25',
  'Lightning Bow shaft': 'k26',
  'Hailstorm Bow shaft': 'k27',
  'Imperial Axe head': 'k28',
  'Skull Crusher head': 'k29',
  'Dragon Mace head': 'k30',
  'Ghost blade': 'k31',
  'Lion blade': 'k32',
  'Crusader Armor piece': 'k33',
  'Crusader Helmet fragment': 'k34',
  'Crusader Boots part': 'k35',
  'Crusader Gauntlets part': 'k36',
  'Crusader shield part': 'k37',
  'Royal Armor piece': 'k38',
  'Royal Helmet fragment': 'k39',
  'Royal Boots part': 'k40',
  'Royal Gauntlets part': 'k41',
  'Royal shield part': 'k42',
  'Ghost Armor part': 'k43',
  'Ghost Helmet fragment': 'k44',
  'Ghost Boots part': 'k45',
  'Ghost Gloves part': 'k46',
  'Lion Armor part': 'k47',
  'Lion Helmet fragment': 'k48',
  'Lion Boots part': 'k49',
  'Lion Gloves part': 'k50',
  'Demon Robe piece': 'k51',
  'Demon Circlet fragment': 'k52',
  'Demon Shoes part': 'k53',
  'Demon Bracers part': 'k54',
  'Divine Robe piece': 'k55',
  'Divine Circlet fragment': 'k56',
  'Divine Shoes part': 'k57',
  'Divine Bracers part': 'k58',
  'Storm Cloak part': 'k59',
  'Durable Cloak part': 'k60',
  'Blessed Cloak part': 'k61',
  'Council Armor part': 'k78',
  'Council Helmet part': 'k79',
  'Council Boots part': 'k80',
  'Council Gauntlets part': 'k81',
  'Council Shield part': 'k82',
  'Griffin Armor part': 'k83',
  'Griffin Helmet part': 'k84',
  'Griffin Boots part': 'k85',
  'Griffin Gloves part': 'k86',
  'Celestial Armor part': 'k87',
  'Celestial Helmet part': 'k88',
  'Celestial Boots part': 'k89',
  'Celestial Bracers part': 'k90',
  'Griffin Knife part': 'k91',
  'Minotaur Sword part': 'k92',
  'Phoenix Sword part': 'k93',
  'Heavy Fauchard part': 'k94',
  'Guisarme part': 'k95',
  'Meteor Bow part': 'k96',
  'Nightfall Bow part': 'k97',
  'Black Morningstar part': 'k98',
  'Maiming Bulawa part': 'k99',
  'Assault Cape part': 'k100',
  'Craftsman Apron part': 'k101',
  'Stoneskin Cloak part': 'k102',
  'Poniard part': 'k103',
  'Lightbane Katana part': 'k104',
  'Doom Warglaive part': 'k105',
  'Decimation Harpoon part': 'k106',
  'Sinister Ranseur part': 'k107',
  'Heartstriker Bow part': 'k108',
  'Windstalker Bow part': 'k109',
  'Malificent Maul part': 'k110',
  'Brutalizer Flail part': 'k111',
  'Manticore Armor part': 'k112',
  'Manticore Helmet part': 'k113',
  'Manticore Boots part': 'k114',
  'Manticore Gloves part': 'k115',
  'Overseer Shield part': 'k116',
  'Overseer Armor part': 'k117',
  'Overseer Helmet part': 'k118',
  'Overseer Boots part': 'k119',
  'Overseer Gauntlets part': 'k120',
  'Discarnate Robe part': 'k121',
  'Discarnate Circlet part': 'k122',
  'Discarnate Shoes part': 'k123',
  'Discarnate Bracers part': 'k124',

  'Chain mail': 'a03',
  'Silver cuirass': 'a04',
  'Mithril armor': 'a05',
  'Steel helmet': 'a08',
  'Silver helmet': 'a09',
  'Mithril helmet': 'a10',
  'Silver boots': 'a14',
  'Mithril boots': 'a15',
  'Silver gauntlets': 'a19',
  'Mithril gauntlets': 'a20',
  'Bronze shield': 'a23',
  'Silver shield': 'a24',
  'Mithril shield': 'a25',
  'Royal Guard Cape': 'a26',
  'Order Armor': 'a27',
  'Order Helmet': 'a28',
  'Order Boots': 'a29',
  'Order Gauntlets': 'a30',
  'Order Shield': 'a31',
  'Hunter Armor': 'a32',
  'Hunter Helmet': 'a33',
  'Hunter Boots': 'a34',
  'Hunter Gloves': 'a35',
  'Clarity Robe': 'a36',
  'Clarity Circlet': 'a37',
  'Clarity Shoes': 'a38',
  'Clarity Bracers': 'a39',
  'Crusader Armor': 'a45',
  'Crusader Helmet': 'a46',
  'Crusader Boots': 'a47',
  'Crusader Gauntlets': 'a48',
  'Crusader Shield': 'a49',
  'Royal Armor': 'a50',
  'Royal Helmet': 'a51',
  'Royal Boots': 'a52',
  'Royal Gauntlets': 'a53',
  'Royal Shield': 'a54',
  'Ghost Armor': 'a55',
  'Ghost Helmet': 'a56',
  'Ghost Boots': 'a57',
  'Ghost Gloves': 'a58',
  'Lion Armor': 'a59',
  'Lion Helmet': 'a60',
  'Lion Boots': 'a61',
  'Lion Gloves': 'a62',
  'Demon Robe': 'a63',
  'Demon Circlet': 'a64',
  'Demon Shoes': 'a65',
  'Demon Bracers': 'a66',
  'Divine Robe': 'a67',
  'Divine Circlet': 'a68',
  'Divine Shoes': 'a69',
  'Divine Bracers': 'a70',
  'Storm Cloak': 'a71',
  'Durable Cloak': 'a72',
  'Blessed Cloak': 'a73',
  'Council Armor': 'a78',
  'Council Helmet': 'a79',
  'Council Boots': 'a80',
  'Council Gauntlets': 'a81',
  'Council Shield': 'a82',
  'Griffin Armor': 'a83',
  'Griffin Helmet': 'a84',
  'Griffin Boots': 'a85',
  'Griffin Gloves': 'a86',
  'Celestial Armor': 'a87',
  'Celestial Helmet': 'a88',
  'Celestial Boots': 'a89',
  'Celestial Bracers': 'a90',
  'Assault Cape': 'a100',
  'Craftsman Apron': 'a101',
  'Stoneskin Cloak': 'a102',
  'Short sword': 'w02',
  'Long sword': 'w03',
  'Widow sword': 'w04',
  'Knight\'s sword': 'w05',
  'Elven sword': 'w06',
  'Rapier': 'w07',
  'Long spear': 'w09',
  'Lance': 'w10',
  'Elven spear': 'w11',
  'Halberd': 'w12',
  'Steel dagger': 'w15',
  'Silver dagger': 'w16',
  'Mithril dagger': 'w17',
  'Wooden Bow': 'w19',
  'Long Bow': 'w20',
  'Elven Bow': 'w21',
  'Forest Bow': 'w22',
  'Bone club': 'w24',
  'Heavy club': 'w25',
  'Steel axe': 'w26',
  'Mithril axe': 'w27',
  'Champion Sword': 'w28',
  'Trident': 'w29',
  'Hunter Bow': 'w30',
  'War hammer': 'w31',
  'Hunter dagger': 'w32',
  'Thundersoul Sword': 'w33',
  'Doomblade Sword': 'w34',
  'Eclipse': 'w35',
  'Guard\'s Spear': 'w36',
  'King\'s Defender': 'w37',
  'Raging Lance': 'w38',
  'Composite Bow': 'w39',
  'Lightning Bow': 'w40',
  'Hailstorm Bow': 'w41',
  'Imperial Axe': 'w42',
  'Skull Crusher': 'w43',
  'Dragon Mace': 'w44',
  'Ghost dagger': 'w45',
  'Lion Knife': 'w46',
  'Griffin Knife': 'w91',
  'Minotaur Sword': 'w92',
  'Phoenix Sword': 'w93',
  'Heavy Fauchard': 'w94',
  'Guisarme': 'w95',
  'Meteor Bow': 'w96',
  'Nightfall Bow': 'w97',
  'Black Morningstar': 'w98',
  'Maiming Bulawa': 'w99',
  '📕Scroll of Rage': 's01',
  '📕Scroll of Peace': 's02',
  '📗Scroll of Rage': 's03',
  '📗Scroll of Peace': 's04',
  '📘Scroll of Rage': 's05',
  '📘Scroll of Peace': 's06',
  '📙Scroll of Rage': 's07',
  '📙Scroll of Peace': 's08',
  '📕Rare scroll of Rage': 's11',
  '📕Rare scroll of Peace': 's12',
  '📗Rare scroll of Rage': 's13',
  '📗Rare scroll of Peace': 's14',
  '📘Rare scroll of Rage': 's15',
  '📘Rare scroll of Peace': 's16',
  '📙Rare scroll of Rage': 's17',
  '📙Rare scroll of Peace': 's18',
  '🖋Scroll of Engraving': 's50',
  '✒️Scroll of Engraving': 's51',
  '🧟‍♂️ Witchling Robe': 'e101',
  '🧟‍♂️ Witchling Circlet': 'e102',
  '🧟‍♂️ Witchling Shoes': 'e103',
  '🧟‍♂️ Witchling Bracers': 'e104',
  '🧟‍♂️ Witch Robe': 'e105',
  '🧟‍♂️ Witch Circlet': 'e106',
  '🧟‍♂️ Witch Shoes': 'e107',
  '🧟‍♂️ Witch Bracers': 'e108',
  '🧟‍♂️ Walker Armor': 'e109',
  '🧟‍♂️ Walker Helmet': 'e110',
  '🧟‍♂️ Walker Boots': 'e111',
  '🧟‍♂️ Walker Gauntlets': 'e112',
  '🧟‍♂️ Walker Shield': 'e113',
  '🧟‍♂️ Zombie Armor': 'e114',
  '🧟‍♂️ Zombie Helmet': 'e115',
  '🧟‍♂️ Zombie Boots': 'e116',
  '🧟‍♂️ Zombie Gauntlets': 'e117',
  '🧟‍♂️ Zombie Shield': 'e118',
  '🧟‍♂️ Imp Robe': 'e119',
  '🧟‍♂️ Imp Circlet': 'e120',
  '🧟‍♂️ Imp Shoes': 'e121',
  '🧟‍♂️ Imp Bracers': 'e122',
  '🧟‍♂️ Demon Robe': 'e123',
  '🧟‍♂️ Demon Circlet': 'e124',
  '🧟‍♂️ Demon Shoes': 'e125',
  '🧟‍♂️ Demon Bracers': 'e126',
  '🧟‍♂️ Manwolf Armor': 'e127',
  '🧟‍♂️ Manwolf Helmet': 'e128',
  '🧟‍♂️ Manwolf Boots': 'e129',
  '🧟‍♂️ Manwolf Gloves': 'e130',
  '🧟‍♂️ Werewolf Armor': 'e131',
  '🧟‍♂️ Werewolf Helmet': 'e132',
  '🧟‍♂️ Werewolf Boots': 'e133',
  '🧟‍♂️ Werewolf Gloves': 'e134',
  '🧟‍♂️ Fleder Armor': 'e135',
  '🧟‍♂️ Fleder Helmet': 'e136',
  '🧟‍♂️ Fleder Boots': 'e137',
  '🧟‍♂️ Fleder Gloves': 'e138',
  '🧟‍♂️ Nosferatu Armor': 'e139',
  '🧟‍♂️ Nosferatu Helmet': 'e140',
  '🧟‍♂️ Nosferatu Boots': 'e141',
  '🧟‍♂️ Nosferatu Gloves': 'e142',
  '🧟‍♂️ Witchling Staff': 'e143',
  '🧟‍♂️ War Club': 'e144',
  '🧟‍♂️ Imp Bow': 'e145',
  '🧟‍♂️ Imp Whip': 'e146',
  '🧟‍♂️ Manwolf Knife': 'e147',
  '🧟‍♂️ Fleder Scimitar': 'e148',
  '🧟‍♂️ Witch Staff': 'e149',
  '🧟‍♂️ Walker Club': 'e150',
  '🧟‍♂️ Demon Bow': 'e151',
  '🧟‍♂️ Demon Whip': 'e152',
  '🧟‍♂️ Werewolf Knife': 'e153',
  '🧟‍♂️ Nosferatu Rapier': 'e154',
  '🎟Gift Coupon \'Pig\'': '614',
  '🎟Gift Coupon \'Horse\'': '615',
  '🎟Gift Coupon \'Owl\'': '616',
  '🎟Gift Coupon \'Mouse\'': '617',
  '🎟Gift Coupon \'Gopher\'': '622',
  '🎟Gift Coupon \'Ants\'': '623',
  '🎟Gift Coupon \'Spider\'': '624',
  '🎟Gift Coupon \'Haunted\'': '625',
  '🎟Gift Coupon \'Camel\'': '626',
};
