/* eslint-disable quote-props */

export default {
  'Thread': '01',
  'Stick': '02',
  'Pelt': '03',
  'Bone': '04',
  'Coal': '05',
  'Charcoal': '06',
  'Powder': '07',
  'Iron ore': '08',
  'Cloth': '09',
  'Silver ore': '10',
  'Bauxite': '11',
  'Magic stone': '13',
  'Sapphire': '15',
  'Solvent': '16',
  'Ruby': '17',
  'Hardener': '18',
  'Steel': '19',
  'Leather': '20',
  'Bone powder': '21',
  'String': '22',
  'Coke': '23',
  'Rope': '31',
  'Metal plate': '33',
  'Metallic fiber': '34',
  'Crafted leather': '35',
  'Stinky Sumac': '39',
  'Mercy Sassafras': '40',
  'Cliff Rue': '41',
  'Love Creeper': '42',
  'Wolf Root': '43',
  'Swamp Lavender': '44',
  'White Blossom': '45',
  'Ilaves': '46',
  'Ephijora': '47',
  'Storm Hyssop': '48',
  'Cave Garlic': '49',
  'Yellow Seed': '50',
  'Tecceagrass': '51',
  'Spring Bay Leaf': '52',
  'Ash Rosemary': '53',
  'Sanguine Parsley': '54',
  'Sun Tarragon': '55',
  'Maccunut': '56',
  'Dragon Seed': '57',
  'Queen\'s Pepper': '58',
  'Plasma of abyss': '59',
  'Ultramarine dust': '60',
  'Ethereal bone': '61',
  'Itacory': '62',
  'Assassin Vine': '63',
  'Kloliarway': '64',
  'Astrulic': '65',
  'Flammia Nut': '66',
  'Plexisop': '67',
  'Mammoth Dill': '68',
  'Silver dust': '69',
  'Hay': '518',
  'Corn': '519',
  'Hamsters': '520',
  'Cheese': '521',
  'Zombie Chest': 'ch1',
  'Vial of Rage': 'p01',
  'Potion of Rage': 'p02',
  'Bottle of Rage': 'p03',
  'Vial of Peace': 'p04',
  'Potion of Peace': 'p05',
  'Bottle of Peace': 'p06',
  'Vial of Greed': 'p07',
  'Potion of Greed': 'p08',
  'Bottle of Greed': 'p09',
  'Vial of Nature': 'p10',
  'Potion of Nature': 'p11',
  'Bottle of Nature': 'p12',
  'Vial of Mana': 'p13',
  'Potion of Mana': 'p14',
  'Bottle of Mana': 'p15',
  'Vial of Twilight': 'p16',
  'Potion of Twilight': 'p17',
  'Bottle of Twilight': 'p18',
  'Vial of Morph': 'p19',
  'Potion of Morph': 'p20',
  'Bottle of Morph': 'p21',
};
